# Generated by Django 4.1.1 on 2022-12-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminario',
            name='horaIns',
            field=models.TimeField(max_length=8),
        ),
    ]
