# Generated by Django 4.1.1 on 2022-12-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioApi', '0002_alter_seminario_horains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminario',
            name='horaIns',
            field=models.TimeField(),
        ),
    ]
